lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
remote_theme: CloudCannon/hydra-jekyll-template
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge